rmbolger/Posh-ACME

Posh-ACME/DnsPlugins/Azure.ps1

Initial Azure DNS plugin

---

Posh-ACME/DnsPlugins/Cloudflare-Readme.md
Posh-ACME/DnsPlugins/Cloudflare.ps1

Cloudflare DNS Plugin

---

Posh-ACME/Public/New-PACertificate.ps1

Hi,
PluginArgs wasn't passed anymore.
Best regards
Julian

PluginArgs wasn't passed

---

Posh-ACME/DnsPlugins/GoDaddy-Readme.md
Posh-ACME/DnsPlugins/GoDaddy.ps1

Hello,
I've written a DNS plugin for GoDaddy that we use internally and thought that I'd share it with the community. 
Please let me know what you think!
Thanks,
Rukas

Add GoDaddy DNS Plugin

---

Posh-ACME/DnsPlugins/Zonomi-Readme.md
Posh-ACME/DnsPlugins/Zonomi.ps1

A DNS plugin for https://zonomi.com

Zonomi DNS Plugin

---

Posh-ACME/DnsPlugins/NS1-Readme.md
Posh-ACME/DnsPlugins/NS1.ps1

https://ns1.com
The `NS1Key` parameter is a SecureString object which puts it in the "only works on Windows" category for the time being.

Added NS1 plugin

---

Posh-ACME/DnsPlugins/GoDaddy.ps1

Fix issue  #50 where the record may not be at the top of the zone.

Fix GoDaddy for records outside of apex domain

---

Posh-ACME/DnsPlugins/Dynu-Readme.md
Posh-ACME/DnsPlugins/Dynu.ps1

Only tested on PowerShell Core 6.1 preview (all I have access to on Ubuntu Bionic), would appreciate a test run from Windows/lower versions.
LMK if you want my Dynu credentials for that purpose.

Add Dynu DNS provider

---

Posh-ACME/DnsPlugins/Azure-Readme.md

For leveraging an existing Azure context in the Azure plugin

Powershell example for using existing auth token

---

Posh-ACME/DnsPlugins/Azure.ps1
Posh-ACME/Private/Get-DateTimeOffsetNow.ps1
Tests/Azure.Tests.ps1

Fix for Issue #57 and added a few tests around the issue for good measure.

Fixed Connect-AZTenant to evaluate token expiration correctly

---

Posh-ACME/DnsPlugins/DeSEC-Readme.md
Posh-ACME/DnsPlugins/DeSEC.ps1

https://desec.io/#!/en/product/dnshosting
https://desec.io/docs.html
TODO: support batch API

Add support for DeSEC DNS Hosting

---

Posh-ACME/DnsPlugins/BlueCat-Readme.md
Posh-ACME/DnsPlugins/BlueCat.ps1

I reworked my organization specific BlueCat DNS plugin into something flexible enough for public use. I was previously copying the source files into the module install path but I've had an item on my roadmap to contribute. I followed the powershell and readme structure of existing plugins, but please let me know if I need to improve or change anything.
Thank you for all of your work.

BlueCat DNS Plugin

---

Posh-ACME/DnsPlugins/OVH-Readme.md
Posh-ACME/DnsPlugins/OVH.ps1

This resolves issue #79 by adding an OVH plugin.
The setup is a bit more cumbersome than other plugins due to OVH's...unique...API credential creation process. Details are in the usage guide.

Added OVH plugin and readme

---

Posh-ACME/DnsPlugins/Windows.ps1

Also adding optional parameter to specify the DNS Zone

Fix case sensitivity issue when record name case doesn't match zone case on the server

---

Posh-ACME/DnsPlugins/FreeDNS-Readme.md
Posh-ACME/DnsPlugins/FreeDNS.ps1

This change adds a [Free DNS](https://freedns.afraid.org) plugin and readme which will address issue #143.

Add FreeDNS plugin

---

Posh-ACME/DnsPlugins/Dreamhost-Readme.md
Posh-ACME/DnsPlugins/Dreamhost.ps1

Tested against my own Dreamhost account with success.

Add Dreamhost DnsPlugin

---

Posh-ACME/DnsPlugins/Domeneshop-Readme.md
Posh-ACME/DnsPlugins/Domeneshop.ps1

This branch adds DNS plugin for provider Domeneshop based on their BETA API. Readme includes link to documentation which has signup instructions.

Add DNS plugin for DNS provider Domeneshop (https://domene.shop/)

---

Posh-ACME/DnsPlugins/Unoeuro-readme.md
Posh-ACME/DnsPlugins/Unoeuro.ps1

Hi,
I've created a Unoeuro plugin for Posh-ACME. Wonderful module. I use this Unoeuro plugin for my domains and wish to share.
Tested with single, multi and wildcart domains.

Unoeuro plugin

---

Posh-ACME/DnsPlugins/PointDNS-Readme.md
Posh-ACME/DnsPlugins/PointDNS.ps1

Adds support for DNS zones hosted at PointHQ / PointDNS

Adds PointDNS plugin support.

---

Posh-ACME/DnsPlugins/Yandex-Readme.md
Posh-ACME/DnsPlugins/Yandex.ps1

Adds support for DNS zones hosted at Yandex (https://connect.yandex.com/)

Adds Yandex plugin

---

Posh-ACME/DnsPlugins/Loopia-Readme.md
Posh-ACME/DnsPlugins/Loopia.ps1

This change addresses issue #212 and provides a [Loopia](https://www.loopia.com/loopiadns/) DNS plugin and readme.

Add Loopia DNS plugin

---

Posh-ACME/DnsPlugins/Selectel-Readme.md
Posh-ACME/DnsPlugins/Selectel.ps1

Hi, @rmbolger. I'm here again and this is one more new plugin)

Adds Selectel.ru plugin

---

Posh-ACME/DnsPlugins/Regru-Readme.md
Posh-ACME/DnsPlugins/Regru.ps1

Adds support for DNS zones hosted at Reg.ru (https://reg.ru/)

Adds Reg.ru plugin

---

Posh-ACME/DnsPlugins/Linode-Readme.md

Fix non-secure parameter reference

Non-windows should use the LITokenInsecure parameter

---

Posh-ACME/DnsPlugins/PointDNS-Readme.md

PointDNS: non-windows uses PDKeyInsecure

---

Posh-ACME/DnsPlugins/NameSilo-Readme.md
Posh-ACME/DnsPlugins/NameSilo.ps1

Add NameSilo as a supported DNS provider.

NameSilo Plugin

---

Posh-ACME/Public/New-PAAccount.ps1

this PR removes trailing query parameters for issue #289

remove query parameters from location header response

---

Posh-ACME/DnsPlugins/Azure-Readme.md
Posh-ACME/DnsPlugins/Azure.ps1

Add support for different Azure cloud environments

---

Posh-ACME/Plugins/UKFast-Readme.md
Posh-ACME/Plugins/UKFast.ps1

Hi 
This plugins supports the UKFast SafeDNS hosting provider for the ACME DNS-01 challenge.
I've followed the structure of the existing plugins as much as possible for easy maintenance.
Thanks :)

Add ukfast dns plugin

---

Posh-ACME/Plugins/Azure.ps1

This change addresses issue #346 and updates the code path for `AZUseIMDS` to support Azure Automation which uses a different metadata endpoint based on an environment variable.

Fix Azure plugin to support IMDS within Azure Automation

---

Posh-ACME/Plugins/Aurora-Readme.md
Posh-ACME/Plugins/Aurora.ps1

Initial version of the DNS Aurora-Plugin (https://pcextreme.nl/)

Aurora-Plugin-v2021.0522.1930

---

Posh-ACME/Plugins/Aurora-Readme.md
Posh-ACME/Plugins/Aurora.ps1

Made some small adjustments. Had some issues with previous version with PowerShell Core.
Now tested on PowerShell 7 (Windows).

Change Aurora DNS

---

Posh-ACME/Plugins/CoreNetworks-Readme.md
Posh-ACME/Plugins/CoreNetworks.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/CoreNetworks.md
docs/Plugins/index.md

Hi @rmbolger,
as discussed (#381) here the Pull Request for my Plugin.
Your review is appreciated. I'm new in this area of development.
Regards,
Daniel

Added plugin for core-networks.de

---

Posh-ACME/Plugins/TotalUptime.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/TotalUptime.md
docs/Plugins/index.md

Hi,
I've developed a plugin to facilitate creating ACME DNS-01 Challenges via the [TotalUptime](https://www.totaluptime.com) API 
I've developed and tested it following the Plugin development guide.
Any comments or reviews are greatly appreciated .
Thanks :)

Added TotalUptime DNS Plugin

---

Posh-ACME/Plugins/Loopia.ps1

Found solution here acmesh-official/acme.sh#3964
Solves #424

Fix for Loopia plugin since API change

---

Posh-ACME/Plugins/Porkbun.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/Porkbun.md
docs/Plugins/index.md

Adding a plugin to support https://porkbun.com DNS. 
I cannot test IDN support, as I don't have a domain that uses it, and their documentation isn't clear on what format the API expects.
Please let me know if there's any mistakes or anything I should change.
Thanks!

Add Porkbun plugin and documentation

---

Posh-ACME/Plugins/GCloud.ps1
docs/Plugins/GCloud.md

Addresses issue #451 by adding a `GCProjectId` string array parameter that accepts one or more Google Cloud project IDs containing the zones needing to be modified by the plugin.
The parameter is optional and only required if
- The zones to modify don't reside in the same project as the service account reference by `GCKeyFile`
- The zones to modify reside in more than one project

Update GCloud to support for querying additional projects

---

Posh-ACME/Plugins/Bunny.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/Bunny.md
docs/Plugins/index.md

This pull request implements a DNS provider for https://bunny.net DNS zones.

Implement Bunny.net DNS Provider

---

Posh-ACME/Plugins/SSHProxy-Readme.md
Posh-ACME/Plugins/SSHProxy.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/SSHProxy.md
docs/Plugins/index.md

As requested in issue #470 , a pull request for code and docs

SSHProxy DNS Plugin

---

Posh-ACME/Plugins/GoogleDomains.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/GoogleDomains.md
docs/Plugins/index.md

This plugin implements a provider specifically for DNS based acme challenges via Google Domains.

Implement Google Domains plugin

---

Posh-ACME/Plugins/ZoneEdit.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/ZoneEdit.md
docs/Plugins/index.md

This plugin addresses issue #495

Add ZoneEdit Plugin

---

Posh-ACME/Plugins/PowerDNS.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/PowerDNS.md
docs/Plugins/index.md

Add PowerDNS plugin and guide

---

Posh-ACME/Plugins/WEDOS.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/WEDOS.md
docs/Plugins/index.md

Add WEDOS plugin and guide 

---

Posh-ACME/Plugins/WebsupportSK.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/WebsupportSK.md
docs/Plugins/index.md

Addresses issue #540 in which users of Active24 are being migrated to a new provider with a different API and the old Active24 API no longer works.

Add Websupport.sk plugin

---

Posh-ACME/Plugins/DomainOffensive.ps1
docs/Plugins/DomainOffensive.md

Hi,
we are moving our API to a different subdomain (the old one will continue to work for now),
I also have updated the links to the documentation

update DomainOffensive plugin

---

Posh-ACME/Plugins/Porkbun.ps1

This change is primarily to address issue #570 in which Porkbun has published that the API endpoint is changing from `porkbun.com` to `api.porkbun.com`. The new name is live and the old name scheduled for decom on 2024-12-01.
Instead of hard coding the new endpoint, it's now configurable via an optional `PorkbunAPIHost` parameter which has `api.porkbun.com` as the default. Existing users should not need to make any changes to their PluginArgs.
There's also a bit of minor refactoring in the plugin including a new retry mechanic for API calls. During testing against the new endpoint, the plugin was frequently getting HTTP 503 (temporarily unavailable) errors. There's no documentation about any explicit rate limiting, but that's what it felt like. So if any given call gets a 503 error, the …

Update Porkbun with new API endpoint

---

docs/Plugins/WEDOS.md

Hi, Wedos had some change in naming and URLs and old URLS were no longer working.

Update WEDOS.md - fix URLs

---

Posh-ACME/Plugins/Netcup.ps1
Posh-ACME/Private/Import-PluginDetail.ps1
docs/Plugins/Netcup.md
docs/Plugins/index.md

Adds Netcup plugin and guide as requested in #602 
This provider has an abnormally long propagation delay to their authoritative nameservers. Updates take at least 10 minutes, but reports from other clients say as long as 15-20 minutes.

Add Netcup plugin and guide
