Posh-ACME/DnsPlugins/AcmeDns.ps1
Adds a `AcmeDns` plugin which addresses issue #1 and #2.
This is likely going to be a fairly unique plugin because of the intended acme-dns workflow. When a cert is first created, each name will have a new acme-dns "registration" which generates a unique subdomain on the acme-dns server. Those subdomains need to be manually registered as CNAMEs targets for their associated challenge records. So the plugin will display an interactive prompt informing the user of what records to add and pause waiting for the user to press a key.
After that, things proceed as normal.  Renewals and new orders with the same names do not require user interaction because the CNAMEs have already been created and the credentials are saved to the account profile just like other plugin parameters.
=> Initial Acme-Dns plugin

Posh-ACME/DnsPlugins/GCloud-Readme.md, Posh-ACME/DnsPlugins/GCloud.ps1, Posh-ACME/Private/ConvertFrom-BCKey.ps1, Posh-ACME/Private/Import-Pem.ps1, Posh-ACME/Private/New-Jws.ps1
Adds a `GCloud` plugin which addresses issue #2 
The following additional function changes are included as well.
There is a new private function, `ConvertFrom-BCKey` which takes a BouncyCastle private key pair and converts it to a .NET `AsymmetricAlgorithm` object.
`Import-Pem` now accepts a string as an alternative input to a file.
`New-Jws` has two new switches. `-Compact` outputs in JWS Compact Serialization format. `-NoHeaderValidation` allows creation of non-ACME related JWSs.
=> Initial GCloud plugin

Posh-ACME/DnsPlugins/Windows-Readme.md, Posh-ACME/DnsPlugins/Windows.ps1
Adds a `Windows` plugin which addresses issue #2.
Relies on Microsoft `DnsServer` and `CimCmdlets` modules. Currently untested on anything earlier than Windows 10 and Server 2016. But should work on any OSes that support those modules.
=> Initial Windows plugin

Posh-ACME/DnsPlugins/Azure.ps1
Hi,
little bug found on using an azure subscription with several DNS zones:
Write-Verbose threw an error when using an Azure subscriptions with multiple DNS zones:
```
Get-AZZoneId : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.0\DnsPlugins\Azure.ps1:21 char:21
+     if (!($zoneID = Get-AZZoneId $RecordName $AZSubscriptionId)) {
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-AZZoneId], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgument,Get-AZZoneId
```
Best regards
Julian
=> Fix for multiple DNS zones in subscription

Posh-ACME/DnsPlugins/AcmeDns.ps1, Posh-ACME/DnsPlugins/Azure.ps1, Posh-ACME/DnsPlugins/DMEasy.ps1, Posh-ACME/DnsPlugins/DOcean.ps1, Posh-ACME/DnsPlugins/GCloud.ps1, Posh-ACME/DnsPlugins/GoDaddy.ps1, Posh-ACME/DnsPlugins/Infoblox.ps1, Posh-ACME/DnsPlugins/README.md, Posh-ACME/Posh-ACME.psm1, Posh-ACME/Private/Export-PACertFiles.ps1, Posh-ACME/Private/Get-Nonce.ps1, Posh-ACME/Private/Invoke-ACME.ps1, Posh-ACME/Private/Update-PAOrder.ps1, Posh-ACME/Private/Update-PAServer.ps1, Posh-ACME/Public/Get-PAAuthorizations.ps1
This change addresses issue #27 which requests the addition of the `-UseBasicParsing` flag to all instances of `Invoke-WebRequest` and `Invoke-RestMethod`.
Because `-UseBasicParsing` is a deprecated switch as of PowerShell Core 6, it is implemented as a module-wide variable called `$script:UseBasic` which is a hashtable that contains `UseBasicParsing=$true` but only if the switch still exists. Otherwise, it's just an empty hashtable.
All current calls to the two functions have `@script:UseBasic` added to them and all future calls should as well. We'll have to be diligent when reviewing new plugin requests.
=> Add -UseBasicParsing to all remote calls

Posh-ACME/DnsPlugins/DNSimple-Readme.md, Posh-ACME/DnsPlugins/DNSimple.ps1
This change adds a [DNSimple](https://dnsimple.com) plugin and readme. The `DSToken` parameter is a securestring which puts it in the "only works on Windows" category for the time being.
=> Add DNSimple plugin

Posh-ACME/DnsPlugins/LuaDns-Readme.md, Posh-ACME/DnsPlugins/LuaDns.ps1
https://www.luadns.com
The `LuaCredential` parameter is a pscredential object which puts it in the "only works on Windows" category for the time being.
=> Added LuaDns plugin

Posh-ACME/DnsPlugins/Linode-Readme.md, Posh-ACME/DnsPlugins/Linode.ps1
https://www.linode.com/
The `LIToken` parameter is a SecureString object which puts it in the "only works on Windows" category for the time being.
=> Added Linode plugin

Posh-ACME/DnsPlugins/Azure-Readme.md, Posh-ACME/DnsPlugins/Azure.ps1
Instead of passing in a tenant and credentials, you can instead pass in a token that you can get from various places, e.g. the MSI local endpoint or the Azure-CLI 2.0 "az account get-access-token --resource xxx" command.
=> Add support for provided Azure access token and IMDS

Posh-ACME/DnsPlugins/Rackspace-Readme.md, Posh-ACME/DnsPlugins/Rackspace.ps1
This change adds a [Rackspace Cloud DNS](https://www.rackspace.com/cloud/dns) plugin.
It includes two parameter sets that distinguish between `-RSApiKey` and `-RSApiKeyInsecure` parameters  so that the non-Windows folks can still use it in a "less secure" mode.
=> Add Rackspace DNS provider

Posh-ACME/DnsPlugins/ClouDNS-Readme.md, Posh-ACME/DnsPlugins/ClouDNS.ps1
This change adds a [ClouDNS](https://www.cloudns.net/aff/id/224075/) provider plugin.
It includes two parameter sets that distinguish between `-CDPassword` and `-CDPasswordInsecure` parameters  so that the non-Windows folks can still use it in a "less secure" mode.
=> Add ClouDNS provider

Posh-ACME/DnsPlugins/Aliyun-Readme.md, Posh-ACME/DnsPlugins/Aliyun.ps1
This change adds a [Aliyun (Alibaba Cloud)](https://www.alibabacloud.com/product/dns) DNS provider plugin.
It includes two parameter sets that distinguish between `-AliSecret` and `-AliSecretInsecure` parameters  so that the non-Windows folks can still use it in a "less secure" mode.
=> Add Aliyun (Alibaba Cloud) provider

Posh-ACME/DnsPlugins/Gandi-Readme.md, Posh-ACME/DnsPlugins/Gandi.ps1
This change adds a [Gandi](https://wwwgandi.net) DNS provider plugin.
It includes two parameter sets that distinguish between `-GandiToken` and `-GandiTokenInsecure` parameters  so that the non-Windows folks can still use it in a "less secure" mode.
=> Add Gandi v4 LiveDNS Plugin

Posh-ACME/DnsPlugins/Azure.ps1, Tests/Azure.Tests.ps1
The content type of the body of the `oauth2/token` request made in the Azure DNS plugin is `application/x-www-form-urlencoded`. The `client_id` and `client_secret` parameters must therefore be URL-encoded to allow characters such as '&' to be used in values.
This pull request adds the necessary url-encoding.
=> URL-encode the Azure client id and secret

Posh-ACME/Public/New-PACertificate.ps1, Posh-ACME/Public/New-PAOrder.ps1
Commit d505fae771b9eba0507154ccfdd2aa27ab7491ac changed `Get-PAOrder` so that it returns `$null` instead of throwing an exception.
This pull request removes the try catch around the call to `Get-PAOrder` in [`New-PAOrder`](https://github.com/rmbolger/Posh-ACME/blob/655b15e97f8878f5b236477553bf356653e6796b/Posh-ACME/Public/New-PAOrder.ps1#L26) and [`New-PACertificate`](https://github.com/rmbolger/Posh-ACME/blob/655b15e97f8878f5b236477553bf356653e6796b/Posh-ACME/Public/New-PACertificate.ps1#L70), which I think is now unnecessary.
With this change, errors on refreshing the order (such as failures connecting to the ACME server) will now be surfaced instead of being silently caught and causing a new order or certificate to be created.
=> Remove no longer needed try catches around calls to Get-Order

Posh-ACME/Public/Submit-ChallengeValidation.ps1
`$toValidate` is an array of domain indexes. The [DNS clean-up code](https://github.com/rmbolger/Posh-ACME/blob/655b15e97f8878f5b236477553bf356653e6796b/Posh-ACME/Public/Submit-ChallengeValidation.ps1#L160) is currently iterating over `$toValidate`, but using the loop variable to identify domains instead of looking up the domain index in `$toValidate`.
If a certificate was requested for two domains, but the first was already validated, a DNS record would only have been created for the second domain. The clean-up code would then try and delete a non-existent DNS record for the first domain instead of the record that was created for the second domain.
This pull request changes the DNS clean-up code to use the index from `$toValidate` to access the `$allAuths`, `$DnsAlias` and `$DnsPlugin` …
=> Fix DNS clean-up when TXT records are not created for all domains

Posh-ACME/Private/Export-PACertFiles.ps1, Posh-ACME/Private/Invoke-ACME.ps1, Posh-ACME/Private/New-Jws.ps1, Posh-ACME/Private/Update-PAAccount.ps1, Posh-ACME/Private/Update-PAOrder.ps1, Posh-ACME/Public/Get-PAAuthorizations.ps1, Posh-ACME/Public/New-PACertificate.ps1
This change implements POST-as-GET support as described in [Section 6.3 of ACME draft-16](https://tools.ietf.org/html/draft-ietf-acme-acme-16#section-6.3) and the following community forum posts:
https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380
https://community.letsencrypt.org/t/any-update-on-gets-posts-conversation/73139
Optional POST-as-GET support was added to the Staging and Production Let's Encrypt endpoints on October 25, 2018. It is currently scheduled to become required on November 1, 2019.
=> Implement POST-as-GET support

Posh-ACME/DnsPlugins/IBMSoftLayer-Readme.md, Posh-ACME/DnsPlugins/IBMSoftLayer.ps1
This change adds a plugin for [IBM Cloud DNS](https://www.ibm.com/cloud/dns) (formerly known as SoftLayer).
It includes two parameter sets that distinguish between `-IBMCredential` for Windows and `-IBMUser`/`-IBMKey` for non-Windows so folks can still use it in a "less secure" mode.
=> Add IBMSoftLayer plugin and readme

Posh-ACME/DnsPlugins/Windows.ps1
This change fixes the Windows plugin when used on remote DNS servers in a Windows domain.
Before this, calling
```
New-PACertificate name.example.com -DnsPlugin Windows -PluginArgs @{WinServer='dns.example.com'}
```
would give the error message:
```
Add-DnsServerResourceRecord : Failed to get the zone information for example.com on server NAME.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\2.9.1\DnsPlugins\Windows.ps1:38 char:17
+ ...     $zone | Add-DnsServerResourceRecord -Txt -Name $recShort -Descrip ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (_acme-challenge.name:root/Microsoft/...rResourceRecord) [Add-DnsServerResourceRecord], CimException
+ FullyQualifiedErrorId : WIN32 …
```
=> fix for Windows plugin add dnsParams to DnsServer commands

Posh-ACME/DnsPlugins/AutoDNS-Readme.md, Posh-ACME/DnsPlugins/AutoDNS.ps1
This change adds an [AutoDNS](https://help.internetx.com/x/Qwfj) plugin that works with any provider utilizing the AutoDNS XML gateway provided by [InternetX](https://www.internetx.com/).
It includes two parameter sets that distinguish between `AutoDNSPassword` for Windows and `AutoDNSPasswordInsecure` for non-Windows so folks can still use it in a "less secure" mode.
It will satisfy issue #97 for Schlundtech integration.
=> Add AutoDNS plugin and readme

Posh-ACME/DnsPlugins/Route53-Readme.md, Posh-ACME/DnsPlugins/Route53.ps1
This change addesses issue #115 in order to remove the dependence on the `AwsPowershell` module when using the plugin. It will still prefer and use the module if it's installed and it is still required when using the `R53ProfileName` authentication method.
It utilizes [AWS Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html) which is the latest as of today.
=> Add REST support to Route53 so AwsPowershell module is not required

Posh-ACME/Private/Import-PAConfig.ps1
I suggest changing EA:SilentlyContinue to EA:Ignore in this file because it looks like not very important if this command would not be executed successfully but SilentlyContinue append error message to $Error and after it's rather hard to automatically parse $Error and decide whether script failed with an important reason or it can be ignored.
Didn't checked other files, sorry :( (I think the similar problem could be somewhere else)
=> Ignore Get-Content errors in Import-PAConfig rather than SilentlyIgnore

Posh-ACME/DnsPlugins/Domeneshop.ps1
Using insecure parameters will throw an error.
The PSCredential object is only needed to decrypt the secure string.
Tested using PS Core 6.2.0 on Linux
Signed-off-by: Ørnulf Nielsen <40027793+ornulfn@users.noreply.github.com>
=> Fix for Domeneshop when using insecure parameter

Posh-ACME/Public/Submit-Renewal.ps1, Tutorial.md
Consider scenarios where we are using short lived access tokens for authentication to a DNS provider. The previously supplied token will now no longer be valid, therefore it would be good to be able to supply a new set of PluginArgs in the renewal.
This scenario is applicable in CI/CD workflows. I have run into this issue using the Azure DNS plugin where I use az cli to generate an access token to supply to Posh-ACME. I did not want to supply standing credentials as they would be stored in the .config folder as I would have to manage that.
I realise this could be problematic when multiple DNS plugins are used. Another alternative is to make public the ```Export-PluginArgs``` function. This way people can update them before running the ```Submit-Renewal``` command.
=> Support supplying new PluginArgs on renewal

Posh-ACME/Posh-ACME.psd1, Posh-ACME/Public/Revoke-PAAuthorization.ps1
This change adds the `Revoke-PAAuthorization` function which can be used to revoke cached authorizations for an account. This can be useful for testing plugins to avoid having to constantly create orders for new identifiers that aren't already authorized.
=> Implement Authorization Revocation

Posh-ACME/DnsPlugins/NS1-Readme.md
Update docs to correct the parameter name for the non-secure version of the key
=> Fix Insecure/Non-windows key parameter example

Posh-ACME/DnsPlugins/Hetzner-Readme.md, Posh-ACME/DnsPlugins/Hetzner.ps1
This plugin works against the [Hetzner](https://www.hetzner.de/) DNS provider. It is assumed that you have already setup an account and created the DNS zone(s) you will be working against.
Using Hetzner DNS API requires only your account name or account number and Auth-API-Token which can be found on the [account](https://dns.hetzner.com/) page.
```powershell
$pArgs = @{ HetznerAPIKey='yyyyyyyy' }
New-PACertificate example.com -DnsPlugin Hetzner -PluginArgs $pArgs
```
=> DNS Plugin for Hetzner.de

Posh-ACME/DnsPlugins/GCloud.ps1
Fixes #243
Private zones are useless for ACME requests. Ignore them.
Tested under Server 2019 (thanks for the instdev.ps1 script, development wasn't so hard)
=> Filter to only public Google DNS Zones as a private zone won't help.

Posh-ACME/DnsPlugins/Azure-Readme.md
Hi,
I've made small change to powershell example in Azure DNS plugin README - [(Optional) Using An Existing Access Token section](https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Azure-Readme.md#optional-using-an-existing-access-token).
I've tried to use code sample
```powershell
$token = ($ctx.TokenCache.ReadItems() | ?{ $_.TenantId -eq $ctx.Subscription.TenantId } |
Select -First 1).AccessToken
```
but I've encountered next issue:
```
The provided access token has missing or incorrect audience claim. Expected: https://management.core.windows.net/
At C:\Users\......\Documents\WindowsPowerShell\Modules\Posh-ACME\3.13.0\DnsPlugins\Azure.ps1:346 char:9
+         throw "The provided access token has missing or incorrect aud ...
+ …
```
=> Small change to powershell example in Azure DNS plugin README

Posh-ACME/DnsPlugins/DomainOffensive-Readme.md, Posh-ACME/DnsPlugins/DomainOffensive.ps1
Thanks for your work. Thought I share my DNS Plugin with you that I use for my hoster [Domain Offensive](https://www.do.de/). Hope I didn't oversee anything but if so, feel free to modify it.
This plugin works against the [Domain Offensive](https://www.do.de/) DNS provider. It is assumed that you have already setup an account and created the DNS zone(s) you will be working against.
We need to retrieve an secret API token for the account that will be used to update DNS records. Further information can ba found at [the (german) developer docs.](https://www.do.de/wiki/LetsEncrypt_-_Entwickler).
Your personal API token is specified using the `DomOffToken` or `DomOffTokenInsecure` parameter.
```powershell
$pArgs = @{
DomOffToken = $secureString
}
New-PACertificate example.com -DnsPlugin …
```
=> DNS Plugin: Domain Offensive

Posh-ACME/Private/New-Jws.ps1, Posh-ACME/Public/New-PAAccount.ps1, README.md, Tests/New-Jws.Tests.ps1
This change addresses #258 and adds additional parameters to `New-PAAccount` that support the external account binding feature described in [RFC 8555 section 7.3.4](https://tools.ietf.org/html/rfc8555#section-7.3.4).
- `-ExtAccountKID` accepts a string value for the key identifier provided by the CA
- `-ExtAccountHMACKey` accepts a string value provided by the CA that represents a Base64Url encoded HMAC key.
- `-ExtAccountAlgorithm` accepts a string value from the set `HS256`, `HS384`,`HS512` which indicates the algorithm to use for creating the MAC from the key. The default value is HS256.
The internal `New-Jws` function was modified to support HMAC keys for JWS generation.
The new parameters in `New-PAAccount` were not also exposed in `New-PACertificate`. Users must explicitly create …
=> Add External Account Binding support

Posh-ACME/Public/Submit-Renewal.ps1
Currently the parameter "PluginArgs" in Submit-Renewal only works with ParameterSet 'Specific'.
This change modifies 'AllOrders' and 'AllAccounts to use the PluginArgs if present.
=> PluginArgs for Submit-Renewal -AllOrders & -AllAccounts

Posh-ACME/Private/Export-PACertFiles.ps1, Posh-ACME/Private/Get-AlternateLinks.ps1, Posh-ACME/Private/Get-ChainIssuers.ps1, Posh-ACME/Private/Import-Pem.ps1, Posh-ACME/Private/Invoke-ACME.ps1, Posh-ACME/Private/Split-PemChain.ps1, Posh-ACME/Public/New-PACertificate.ps1, Posh-ACME/Public/New-PAOrder.ps1, Posh-ACME/Public/Set-PAOrder.ps1
This change adds a `-PreferredChain` parameter to `New-PACertificate`, `New-PAOrder`, and `Set-PAOrder` which mimics the functionality [recently introduced](https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#160---2020-07-07) into certbot.
For ACME CAs that offer multiple CA chains via "alternate" link headers, this parameter allows the user to choose which chain to use on a per order/cert basis. Just like certbot, the parameter accepts the Issuer Common Name of any cert in the chain. The first chain with a cert that matches "wins" and all of the resulting cert files are built with that chain. If there are no matches, the default (first) chain is used.
Using `Set-PAOrder -PreferredChain` also allows you regen the cert files with a different chain without needing to get a …
=> Add preferred chain support

Posh-ACME/Public/Get-PAAuthorizations.ps1
Posh-ACME will currently fail if a CA does not return expires time in the authorization object. RFC 8555 7.1.4 does not require the expire time to be set unless the status property is set to "valid". For all other statuses the timestamp is optional. 
An example of an RFC 8555 compliant CA returning auth objects without the expiration is Buypass (https://api.buypass.com/acme/directory and https://api.test4.buypass.no/acme/directory). 
This change fixes it by ignoring the expires property if it does not exist instead of stopping with an exception message.
=> Allow authorization objects without the expires property set

Posh-ACME/Public/Submit-Renewal.ps1
`Submit-Renewal` when used with the `-AllOrders` parameter does not currently behave the same as when used with the current or a specific order. Most notably, invalid orders such as those that were previously attempted and failed are skipped. This is undesirable in an automated renewal setting where a temporary problem may have caused a validation failure.
This change removes the existing decision making logic from the AllOrders code path and lets it pass through to the specific order code path so things work consistently. A side effect of this change is that verbose output will now output lines for each skipped order.
=> Fix Submit-Renewal -AllOrders so it no longer skips invalid or pending orders

Posh-ACME/Plugins/RFC2136-Readme.md, Posh-ACME/Plugins/RFC2136.ps1
This change modifies how the plugin determines a successful nsupdate by checking the exit code rather than trying to parse the output. It also adds an optional `DDNSZone` parameter which adds an explicit zone entry to the update request so that nsupdate doesn't need to make an SOA query to determine the zone. This appears to be necessary in some environments where the DNS server doesn't properly respond to TSIG authenticated SOA queries. Both of these are discussed in more detail in issue #307.
=> Compatibility updates for RFC2136 plugin

Posh-ACME/Plugins/Infomaniak-Readme.md, Posh-ACME/Plugins/Infomaniak.ps1
Hi @rmbloger. 
First of all: Thank you so much for this ACME client.
I added a DNS Plugin for the hoster Infomaniak from Switzerland. 
I did use the plugin on two Windows Servers and a Windows Desktop which all worked well.
I tested:
- example.com
- *.example.com
- sub.example.com
- sub2.sub1.example.com
I've got one question. Is there a way to tell the user if something failed? e.g., the zone hasn't been found? Refer to line [69](https://github.com/Sundypha/Posh-ACME/blob/dns1-infomaniak-plugin/Posh-ACME/Plugins/Infomaniak.ps1#L69) and line [150](https://github.com/Sundypha/Posh-ACME/blob/dns1-infomaniak-plugin/Posh-ACME/Plugins/Infomaniak.ps1#L150) where I could fail gracefully.
Awaiting your review and feedback!
Best
Simon
=> DNS Plugin for Infomaniak.com

Posh-ACME/Plugins/AcmeDns-Readme.md, Posh-ACME/Plugins/AcmeDns.ps1
Hi @rmbolger
Thanks so much for this great tool.
I had a niche need for http support with the acme-dns plugin. I hope it's not a problem to add it to the plugin.
I tested it using `Publish-Challenge`  and it passed.
Sample json to pass though
```
$reg = @{
'_acme-challenge.www.example.com' = @(
'ec6ec1f4-836e-462e-b577-b2f4e04d7291'
'aeb00c77-852b-465e-9b27-984bc6cb12f5'
'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'
'ec6ec1f4-836e-462e-b577-b2f4e04d7291.acmedns.example.com'
)
}
$pArgs = @{
ACMEServer = 'acmedns.example.com'
ACMERegistration = $reg
HTTP = $true
}
```
Please excuse me if I made mistakes, I'm a rookie in git and open source in general (this is my very first PR).
=> add support for acme-dns that uses http

Tutorial.md
I ran into an unexpected issue when I renewed a few certs in a root domain, I wasn't aware of the rate limit special condition, thought it might help to add to the tutorial.
=> Note about renewal limits in tutorial

Posh-ACME/Plugins/All-Inkl-Readme.md, Posh-ACME/Plugins/All-Inkl.ps1
Hi, I need support for the KAS API of all-inkl.com. Therefore I created a new DNS plugin for it.
I already used the plugin on Win10 with PS7.1.3 and on Win2019 with PS5.1. So I'm positive it works with both versions of powershell.
During development I was unsure about the parameters regarding passwords and so on. Some plugins provide additional 'insecure' parameters. When I saw, that you deprecated some of them lately, I went with securestring parameters only. Is this fine?
Also this is the first time I've written that many lines of code in powershell. So don't hesitate to tell me what needs to be done differently :)
It seems as if one could create a test account: https://all-inkl.com/webhosting/test-account/
But I didn't test that yet. So I don't know if the test account supports API …
=> added a new DNS plugin for the All-Inkl.com KAS API

README.md
This changes the reference to Windows PowerShell in the first line to "PowerShell" with a link to the platform requirements as PowerShell 7 (and PSCore) are now supported as well.
=> Correct Windows PowerShell reference in first line.

Posh-ACME/Posh-ACME.psd1, Posh-ACME/Private/ConvertTo-PAAuthorization.ps1, Posh-ACME/Public/Get-PAAuthorization.ps1, Posh-ACME/Public/New-PAAuthorization.ps1, Posh-ACME/Public/New-PreAuthorization.ps1
Some ACME servers may support [pre-authorization](https://datatracker.ietf.org/doc/html/rfc8555#section-7.4.1) which allows users to create and validate authorization objects outside of the normal order lifecycle.
`New-PAAuthorization` enables users to request new authorization objects for a given set of identifiers. If authorization objects already exist for a given identifier, the ACME server will return the existing object.
Currently, the only public ACME CA that seems to support pre-authorization is BuyPass.
=> Added New-PAAuthorization

Posh-ACME/Plugins/ISPConfig.ps1, Posh-ACME/Private/Import-PluginDetail.ps1, docs/Plugins/ISPConfig.md, docs/Plugins/index.md
This change adds a new plugin and guide for the [ISPConfig](https://www.ispconfig.org/) hosting control panel as requested in #380.
=> Add ISPConfig plugin and guide

.github/workflows/pester.yml, CONTRIBUTING.md, Posh-ACME/Private/Export-PluginArgs.ps1, Posh-ACME/Private/Get-EncryptionParam.ps1, Posh-ACME/Private/Set-AltPluginEncryption.ps1, Posh-ACME/Private/Update-PluginEncryption.ps1, Posh-ACME/Public/Get-PAPluginArgs.ps1, Posh-ACME/Public/New-PAAccount.ps1, Posh-ACME/Public/Set-PAAccount.ps1, Tests/Get-EncryptionParam.Tests.ps1, Tests/Set-AltPluginEncryption.Tests.ps1, docs/Guides/Environment-Variable-Reference.md, docs/Guides/Using-SecretManagement.md
This change introduces optional integration with PowerShell [SecretManagement](https://devblogs.microsoft.com/powershell/secretmanagement-and-secretstore-are-generally-available/) as requested in issue #365. The AES key used by the Alternative Plugin Encryption function can now be stored in a supported SecretManagement vault instead of attached directly to the Account config file. A detailed guide for the doc site is included in the change as well as additions to the existing environment variable reference doc.
=> Add SecretManagement support

docs/Plugins/EasyDNS.md
- Example uses deprecated param name
=> Fix example to use secure string param

Posh-ACME/Private/Export-CertPfx.ps1, Posh-ACME/Private/Export-PACertFiles.ps1, Posh-ACME/Public/New-PACertificate.ps1, Posh-ACME/Public/New-PAOrder.ps1, Posh-ACME/Public/Set-PAOrder.ps1, Posh-ACME/en-US/Posh-ACME-help.xml, docs/Functions/New-PACertificate.md, docs/Functions/New-PAOrder.md, docs/Functions/Set-PAOrder.md
Fixes #446
This raises security a bit, allows OpenSSL 3.x to read it without legacy mode, and in general is just a good idea.
As for compatibility, it *should* be well supported. OpenSSL, as far as I know, supports it since 1.1.1, and all earlier versions are out of support upstream. Windows also has no issues with it.
=> Use modern PBES2 for private keys in PFX (fixes #446)

Posh-ACME/Plugins/NameSilo.ps1
NameSilo has made an undocumented API change to the listDomains query, it now returns the domain expiry as an xml property.  This filters out the expiry so the domain can be found again.
=> Fix for NameSilo API change

Posh-ACME/Plugins/All-Inkl.ps1
As mentioned in #459, the SHA1 authentication method with All-Inkl is being deprecated and only plaintext auth will be allowed sometime after December 2022. While the current plugin allows for a plaintext password parameter set, it converts that to SHA1 under the hood to avoid needing to send the plaintext password over the network.
However, since plaintext will be the only allowed method going forward, this needs to change so that the plaintext password is passed as-is.
=> Fix All-Inkl plugin's plaintext KasPwd param to actually send the password in plaintext

Posh-ACME/Private/New-Csr.ps1, Posh-ACME/Public/New-PACertificate.ps1, Posh-ACME/Public/New-PAOrder.ps1, Posh-ACME/Public/Set-PAOrder.ps1, Posh-ACME/en-US/Posh-ACME-help.xml, docs/Functions/New-PACertificate.md, docs/Functions/New-PAOrder.md, docs/Functions/Set-PAOrder.md
Adds a `-Subject` parameter to new orders that allows overriding the default `CN=example.com` generated from the MainDomain on the order. This can be useful for private CAs that allow for additional subject details that public DV CAs don't.
=> Added Subject parameter to New-PACertificate

Posh-ACME/Plugins/RFC2136.ps1
The recent change (a2ff71c) to make the `DDNSNameserver` param optional in the RFC2136 plugin, actually disabled the ability to specify the DNS server manually, since the check to see if the param had been provided was using the wrong variable name. This forced `nsupdate` to always try to detect it via SOA, which could be wrong if people are using split DNS, etc.
=> Fix broken DDNSNameserver param in RFC2136 plugin

Posh-ACME/Public/Revoke-PACertificate.ps1
Hi @rmbolger 
I ran into the problem described in Issue #418. After investigating I identified the part causing the error to be the Add-Type call to add the enum for RevocationReasons. I tested replacing this with the native enum keyword which worked. Enum was introduced in Powershell v5 so this should meet your Powershell version requirements.
As it happens the documentation uses RevocationReasons which the new enum matches as well so the only changes are in the Revoke-PACertificate.ps1 file.
=> Fix for issue #418. Change Add-Type to native enum

docs/Plugins/GoDaddy.md
According to GoDaddy API support there are new limits for API access:
> We have recently updated the account requirements to access parts of our production Domains API. As part of this update, access to these APIs are now limited:
> 
>     Availability API: Limited to accounts with 50 or more domains
>     Management and DNS APIs: Limited to accounts with 10 or more domains and/or an active Discount Domain Club plan.
> 
> If you have lost access to these APIs, but feel you meet these requirements, please reply back with your account number and we will review your account and whitelist you if we have denied you access in error.
> 
> Please note that this does not affect your access to any of our OTE APIs.
> 
> If you have any further questions or need assistance with other API questions, …
=> Add account limits note in GoDaddy.md

Posh-ACME/Private/Update-PAOrder.ps1, Posh-ACME/Public/Get-PACertificate.ps1, Posh-ACME/Public/New-PACertificate.ps1, Posh-ACME/Public/New-PAOrder.ps1, Posh-ACME/Public/Set-PAServer.ps1, Posh-ACME/Public/Submit-Renewal.ps1, Posh-ACME/en-US/Posh-ACME-help.xml, docs/Functions/New-PAOrder.md, docs/Functions/Set-PAServer.md
The [ARI (ACME Renewal Information)](https://www.ietf.org/archive/id/draft-ietf-acme-ari-03.html) draft standard is approaching finalization and the draft-03 version is currently supported in by both Let's Encrypt and Google Trust Services. This change adds ARI support in the module conditionally on the existence of the `renewalInfo` field in the directory endpoint. As other ACME providers add support, it will be enabled automatically once they start publishing that endpoint.
The following user facing changes are part of this PR:
- `ARIId` and `Serial` fields have been added to the output of `Get-PACertificate`
- `DisableARI` switch added to `Set-PAServer` which disables ARI support for the server even it would otherwise be supported. This will primarily be useful if the ARI draft changes …
=> Add ARI support for draft-03

Posh-ACME/Plugins/OnlineNet.ps1, Posh-ACME/Plugins/Scaleway.ps1, Posh-ACME/Private/Import-PluginDetail.ps1, docs/Plugins/OnlineNet.md, docs/Plugins/index.md
This adds a plugin for what appears to be a legacy API for online.net which is now known as Scaleway. But the native Scaleway API is not compatible. This only works for domains managed from [console.online.net](https://console.online.net). It addresses the main part of issue #557.
An different plugin may eventually be necessary if users are migrated to the newer Scaleway API. However, Scaleway support has indicated there are no current plans to migrate users.
=> Add plugin for online.net

Posh-ACME/Plugins/AddrTools.ps1, Posh-ACME/Private/Import-PluginDetail.ps1, docs/Plugins/AddrTools.md, docs/Plugins/index.md
Addresses #572 and adds a basic plugin for `challenges.addr.tools`. Using the plugin requires setting up CNAMEs for challenge aliases beforehand, but is automated after that initial step unless names are added or removed from the certificate.
=> Add AddrTools plugin and guide

Posh-ACME/Posh-ACME.psd1, Posh-ACME/Private/Register-ArgCompleters.ps1, Posh-ACME/Public/Get-PAProfile.ps1, Posh-ACME/Public/New-PACertificate.ps1, Posh-ACME/Public/New-PAOrder.ps1, Posh-ACME/Public/Set-PAOrder.ps1, Posh-ACME/Public/Submit-Renewal.ps1, Posh-ACME/en-US/Posh-ACME-help.xml, docs/Functions/Get-PAProfile.md, docs/Functions/New-PACertificate.md, docs/Functions/New-PAOrder.md, docs/Functions/Set-PAOrder.md
This PR adds support for the initial draft of the ACME Profiles Extension which will be required in order to use the new short-lived cert and IP-address cert options from Let's Encrypt later this year.
https://letsencrypt.org/2025/01/09/acme-profiles/
https://datatracker.ietf.org/doc/draft-aaron-acme-profiles/
https://letsencrypt.org/2025/01/16/6-day-and-ip-certs/
* New function `Get-PAProfile` returns the profiles supported by the current ACME server
* New `-Profile` param on `New-PAOrder`, `Set-PAOrder`, and `New-PACertificate` functions with tab-completion for supported values.
* `Submit-Renewal` will attempt to renew with the same profile value as the previous cert.
* If a new order is requested with a profile that doesn't exist, a warning will be generated and the request will fall …
=> ACME Profiles Support

Posh-ACME/Plugins/Azure.ps1
Believe it or not, there is a way to add certs to Linux systems using PowerShell. However, this method does not present the PS-drive provider Microsoft.PowerShell.Security\Certificate. So the current Azure plugin code checking if the cert is there using cert:\ doesn’t work. I left existing code and just added a "well you didn’t find it, try these two new methods" sort of code. Technically I am pretty sure my method would work in Windows so it might be worth in the future swaping to just that but I cant fully test it. Anyone is welcome to take what I did and make it better. Anyone wanting to import a cert in Linux can use this example code: 
```
#import the PFX to your machines cert store
$StoreName = [System.Security.Cryptography.X509Certificates.StoreName]::My  
$StoreLocation = …
```
=> Update Azure.ps1 | Support for Linux CertThumbprints

Posh-ACME/Plugins/Windows.ps1, docs/Plugins/Windows.md
This pull request introduces a new feature to the `Posh-ACME/Plugins/Windows.ps1` script, allowing users to opt out of using CIM sessions for DNS commandlets. The changes include updates to the `Add-DnsTxt` and `Remove-DnsTxt` functions, as well as documentation updates to reflect the new functionality.
This seems to require less permissions as DNS permissions alone are not enough to establish a CIM Session to the DNS Servers / Domain Controllers.
* [`Posh-ACME/Plugins/Windows.ps1`](diffhunk://#diff-27bb51b36d0d20fa1e6ec508d3ddfce095fc0b1a6b1bc81e6515d0628d7903b9R16-R28): Added a new switch parameter `WinNoCimSession` to the `Add-DnsTxt` and `Remove-DnsTxt` functions. This allows users to choose not to use CIM sessions when running DNS commandlets. The script now checks for this parameter …
=> feat: Add WinNoCimSession parameter to Windows Plugin
